### ISSUE TITLE
Uncaught Exception when using back and forth buttons in the browser

### ISSUE THREAD

**Issue by eporsche** [remix-run/remix-jokes#13]
Using the back and forth button while being logged in. I get this:

![grafik](https://user-images.githubusercontent.com/3265129/146339256-1ff1eff0-201d-4a6e-8bc3-395ce18467c4.png)

**Comment by kentcdodds** [comment]
Thanks for the issue. We're archiving this repository in favor of the project example here: https://github.com/remix-run/remix/tree/main/examples/jokes

If you feel this is still an issue, feel free to open an issue on the Remix repo: https://github.com/remix-run/remix/issues/new/choose

Thanks again!
