### ISSUE TITLE
Double titles/metadata on many pages

### ISSUE THREAD

**Issue by TomerAberbach** [remix-run/remix-jokes#15]
Seems that https://remix-jokes.lol has two `<title>` tags on many pages. Is it maybe that `Meta` always just adds new metadata and does not overwrite parent metadata?

**Comment by kentcdodds** [comment]
Thanks for the issue. We're archiving this repository in favor of the project example here: https://github.com/remix-run/remix/tree/main/examples/jokes

If you feel this is still an issue, feel free to open an issue on the Remix repo: https://github.com/remix-run/remix/issues/new/choose

Thanks again!
