### ISSUE TITLE
2 tutorial bugs: (RSS doesn't work) + (Fly's .dockerignore doesn't work for Prisma)

### ISSUE THREAD

**Issue by cweekly** [remix-run/remix-jokes#18]
Disclaimer: I'm still genuinely excited about Remix, but in stepping through the remix-jokes tutorial I ran into a couple acute issues that left me scratching my head. I feel pretty confident others must have encountered them too. Hoping that posting here might help shed some light. 

**Issue 1: Resource Routes / RSS feature:** 
The tutorial's implementation differs from this repo's, and AFAICT neither of them work.  
https://remix-jokes.lol/jokes.rss (like my follow-along-at-home version) returns a 200 response but there are no joke `<item>`s, just the feed metadata ending with `</ttl>`. I stopped trying to debug it when I realized it wasn't just me. 
  
**Issue 2: Deployment: Prisma vs Fly.io's default `.dockerignore`:**  
The `.dockerignore` file noted in the tutorial and present in this repo, auto-generated by `fly launch`, consists of just one path to ignore: `node_modules`. That's pretty standard and seems reasonable. BUT. Prisma is weird, in that it relies on generating files in `node_modules/prisma` -- which files are not present following `npm install`! (This gives me the heebie-jeebies, even if the Prisma APIs are really nice.) 
So in following the tutorial step-by-step, the `fly deploy` step fails with errors like:  
```
Error: Cannot find module '/root/.npm/_npx/524/lib/node_modules/prisma/scripts/preinstall-entry.js'
```

The only way I could mitigate this problem was to edit the `.dockerignore` file, adding an exclusion to NOT ignore `node_modules/prisma` in particular: 
```
!node_modules/prisma
```
... which fixed the problem. 

But, how did the setup in this repo and/or noted in the tutorial's prose ever work without making this change? 
Thanks in advance for any responses!

**Comment by kentcdodds** [comment]
Thanks for the issue. We're archiving this repository in favor of the project example here: https://github.com/remix-run/remix/tree/main/examples/jokes

If you feel this is still an issue, feel free to open an issue on the Remix repo: https://github.com/remix-run/remix/issues/new/choose

Thanks again!
